services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - coffeedoor-network

  notification-app:
    container_name: notification-app
    image: notification-microservice:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.docker
    depends_on:
      - rabbitmq
    networks:
      - coffeedoor-network

networks:
  coffeedoor-network:
      external: true

volumes:
  rabbitmq-data: 