services:
  notification-app:
    container_name: notification-app
    image: notification-microservice:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.docker
    expose:
      - '9102'
    networks:
      - coffeedoor-network

networks:
  coffeedoor-network:
      external: true
